/**
 * Cumulative review — the part of the course that makes it stick.
 *
 * Teaching a thing once and testing it once produces recognition, not
 * retention. Three strategies are applied here, and they are the reason the
 * course is structured in "acts" rather than as nine independent units:
 *
 *   • RETRIEVAL PRACTICE — the review asks you to produce the answer again,
 *     later, from memory. Re-reading the card would feel easier and teach less.
 *   • SPACING — the questions come back after intervening units, not at the end
 *     of the lesson that introduced them.
 *   • INTERLEAVING — the review round-robins across its source units instead of
 *     marching through them in blocks, so the learner has to work out *which*
 *     idea is being asked about, which is most of what understanding is.
 *
 * Only `core` questions are drawn. That is the whole point of the tier: the
 * course drills the things a learner must walk away holding, and lets the
 * supporting detail be met once and let go.
 *
 * Reviews add no new claims, so they add no new citation burden — each question
 * is reused verbatim, carrying the sources it was already written with. Ids are
 * prefixed so they stay globally unique.
 */
import type { FaithLesson, FaithUnit, Question } from './types';

/** Where a review sits, and which units it draws on (in order of first taught). */
interface ReviewPoint {
  /** The unit the review lesson is appended to — the end of an "act". */
  readonly unitId: string;
  readonly title: string;
  /** Units to draw core questions from, oldest first. */
  readonly draws: readonly string[];
  /** How many questions the review asks. */
  readonly size: number;
}

/**
 * Three acts:
 *   I–III   how the Church began and how the faith came to be defined
 *   IV–VI   what it confesses, and how that confession is prayed
 *   VII–IX  who carried it, where it stands now, and what is still open
 *
 * The final review draws on all nine units — it is the course's last word, and
 * the thing standing between the learner and the last clause of the Creed.
 */
const REVIEW_POINTS: readonly ReviewPoint[] = [
  {
    unitId: 'councils',
    title: 'Recollection · The First Act',
    draws: ['origins', 'martyrs', 'councils'],
    size: 9,
  },
  {
    unitId: 'worship',
    title: 'Recollection · The Second Act',
    // Reaches back into act one on purpose — the Chalcedon material only holds
    // if Ephesus and Theotokos are still in memory when it is asked about.
    draws: ['councils', 'chalcedon', 'doctrine', 'worship'],
    size: 10,
  },
  {
    unitId: 'mystery',
    title: 'Recollection · The Whole Course',
    draws: ['origins', 'martyrs', 'councils', 'chalcedon', 'doctrine', 'worship', 'fathers', 'today', 'mystery'],
    size: 12,
  },
];

/** Every `core` question of a unit, in the order it is taught. */
function coreQuestions(unit: FaithUnit | undefined): Question[] {
  if (!unit) return [];
  return unit.lessons.flatMap((l) => l.questions.filter((q) => q.tier === 'core'));
}

/**
 * Round-robin across the source units: one from the first, one from the second,
 * and so on, then round again. This is the interleaving — consecutive questions
 * come from different units, so the learner cannot coast on context.
 */
function interleave(pools: Question[][], size: number): Question[] {
  const out: Question[] = [];
  const cursors = pools.map(() => 0);
  let exhausted = false;
  while (out.length < size && !exhausted) {
    exhausted = true;
    for (let i = 0; i < pools.length && out.length < size; i++) {
      const pool = pools[i]!;
      const at = cursors[i]!;
      if (at < pool.length) {
        out.push(pool[at]!);
        cursors[i] = at + 1;
        exhausted = false;
      }
    }
  }
  return out;
}

function buildReview(point: ReviewPoint, units: readonly FaithUnit[]): FaithLesson | null {
  const pools = point.draws.map((id) => coreQuestions(units.find((u) => u.id === id)));
  const picked = interleave(pools, point.size);
  if (picked.length === 0) return null;
  return {
    id: `${point.unitId}-review`,
    unitId: point.unitId,
    title: point.title,
    // No teaching cards: a review is retrieval, not re-reading. Being shown the
    // answer again first is exactly what would rob the exercise of its value.
    cards: [],
    questions: picked.map((q) => ({ ...q, id: `review-${point.unitId}-${q.id}` })),
  };
}

/** The units with a cumulative review appended at each act boundary. */
export function withReviews(units: readonly FaithUnit[]): FaithUnit[] {
  return units.map((unit) => {
    const point = REVIEW_POINTS.find((r) => r.unitId === unit.id);
    if (!point) return unit;
    const review = buildReview(point, units);
    return review ? { ...unit, lessons: [...unit.lessons, review] } : unit;
  });
}

/** True for a lesson generated by this module (used by the UI and the tests). */
export function isReviewLesson(lessonId: string): boolean {
  return lessonId.endsWith('-review');
}

export const REVIEW_LESSON_IDS: readonly string[] = REVIEW_POINTS.map((r) => `${r.unitId}-review`);
