/**
 * All user-facing strings — one place for voice consistency and future i18n
 * (CLAUDE.md "Voice": warm, literary, liturgical; never gamified or guilt-driven).
 */
export const copy = {
  tabs: { today: 'Today', hours: 'Hours', word: 'Word', learn: 'Learn', rule: 'Rule', you: 'You', saved: 'Saved' },

  today: {
    account: "The day's account",
    greeting: (name: string) => `Peace to you,\n${name}`,
    streak: 'day streak',
    kept: (n: number, m: number) => `Kept ${n} / ${m}`,
    ruleToday: 'Your rule today',
    commemoration: 'Commemoration of the day',
    journal: 'The journal',
    openJournal: 'Open the journal →',
    resting: 'Resting today',
    emptyTitle: 'Your rule is unwritten',
    emptyBody: 'Begin with a single practice. The lamp is tended, not stormed.',
    toRule: 'Open the Rule',
  },

  rule: {
    head: 'Your rule of life',
    title: 'A living rule',
    subtitle: 'Small and steady. Reorder, measure, or ease it whenever the season turns.',
    add: '＋ Add a practice',
    lighten: 'Lighten the rule for a season',
    groups: { prayer: 'Prayer', word: 'The Word', fast: 'The Fast', devotion: 'Devotion' },
  },

  checkin: {
    keep: 'Mark kept',
    part: 'Kept in part',
    cancel: 'Close',
  },

  lighten: {
    title: 'Tend, don’t storm',
    rest: 'Rest today — the flame stays lit',
    pause: 'Pause one practice',
    lighter: 'Keep a lighter rule',
    note: 'Rest days never break the streak.',
  },

  placeholder: {
    soon: 'Tended soon',
    body: 'This part of the book is still being illuminated.',
  },

  auth: {
    era: 'Anno Martyrum 1742',
    wordmark: 'Pharos',
    coptic: 'ⲡⲓⲫⲁⲣⲟⲥ',
    promise:
      'A guiding light into the faith of the Copts — prayer, fasting, and the Word, one day at a time.',
    begin: 'Begin the journey',
    continueGoogle: 'Continue with Google',
    signingIn: 'Signing in…',
    signInError: 'Sign-in did not complete. Please try again.',
    haveAccount: 'I already keep an account',
    or: 'or',
    withEmail: 'Continue with email',
    signUpTitle: 'Keep an account',
    signUpSub: 'Save your rule so it’s here whenever you return.',
    signInTitle: 'Welcome back',
    signInSub: 'Sign in to return to your rule.',
    email: 'Email',
    password: 'Password',
    createAccount: 'Create account',
    signIn: 'Sign in',
    toSignIn: 'Already have an account? Sign in',
    toSignUp: 'New here? Create an account',
    errors: {
      'invalid-email': 'That email does not look right.',
      'weak-password': 'Use at least four characters.',
      'email-taken': 'An account already keeps that email.',
      'invalid-credentials': 'Those credentials do not match.',
      'confirm-email': 'Check your inbox to confirm your email, then sign in.',
    } as Record<string, string>,
  },

  onboarding: {
    journeyKicker: 'The first question',
    journeyTitle: 'Where are you\non the journey?',
    journeySub: 'Your rule is shaped around the answer. It may be changed at any hour.',
    nameLabel: 'Your first name',
    namePlaceholder: 'What shall we call you?',
    journey: {
      'grew-up': { title: 'I grew up in the Church', sub: 'Deepen a faith I already know' },
      returning: { title: 'I am returning', sub: 'Finding my way back to the rhythm' },
      exploring: { title: 'I am exploring', sub: 'Curious about Coptic Orthodoxy' },
    },
    rhythmKicker: 'Your rule of life',
    rhythmTitle: 'Set the daily\nhours you will keep',
    rhythmSub: 'Small and steady. The lamp is tended, not stormed.',
    lightLamp: 'Light the lamp →',
    continue: 'Continue →',
    notifKicker: 'One last thing',
    notifTitle: 'A gentle word\nat the hour',
    notifSub:
      'Reminders arrive only when a practice is due, in a quiet voice — never to shame, only to tend.',
    notifAllow: 'Allow reminders',
    notifSkip: 'Not now',
  },

  you: {
    head: 'You',
    signOut: 'Sign out',
    switch: 'Switch account',
    addAccount: 'Create another account',
    reminders: 'Reminders',
    theme: 'Appearance',
    themeModes: [
      { key: 'light', label: 'Light' },
      { key: 'dark', label: 'Dark' },
      { key: 'system', label: 'System' },
    ] as const,
    marks: 'The marks',
    about: 'About & attributions',
    privacy: 'Privacy policy',
    terms: 'Terms of service',
    journeyLabel: 'On the journey',
    stats: { streak: 'streak', prayers: 'prayers', wedfri: '% wed/fri' },
    streakTitle: 'The lamp, tended',
    streakBody: 'Keep one practice each day to tend the flame.',
    streakUnit: 'days kept in a row',
    settings: 'Settings',
    textSize: 'Reading text size',
    textSizes: [
      { key: 'sm', label: 'S' },
      { key: 'md', label: 'M' },
      { key: 'lg', label: 'L' },
      { key: 'xl', label: 'XL' },
    ] as const,
    fastingNuance: 'Show fish-allowed nuance',
    aboutBody:
      'Pharos keeps your rule on this device alone. Liturgical and scriptural texts are drawn from the verified sources credited below; anything not yet supplied is clearly marked as a placeholder.',
    attributionsTitle: 'Attributions & sources',
    attributions: [
      {
        title: 'Holy Scripture',
        body: 'The Holy Bible, King James Version (KJV) — public domain. The KJV is the historically approved English translation for Coptic Orthodox use.',
      },
      {
        title: 'The Synaxarium',
        body: 'Daily commemorations from the open “coptic-synaxarium” dataset (randogoth, Codeberg). English text by St. George Coptic Orthodox Church, Chicago. Used in draft pending written permission.',
      },
      {
        title: 'Daily readings · the Katameros',
        body: 'Lectionary references (which passages are read each day) from the Katameros API at katameros.app, an open-source project. The verse text shown is the King James Version.',
      },
      {
        title: 'The liturgical calendar',
        body: 'The Coptic calendar, fasts, and feasts are computed within Pharos (Anno Martyrum dating and the Julian Paschal computus) and cross-checked against published Coptic sources.',
      },
      {
        title: 'The Agpeya',
        body: 'The Coptic Book of Hours (the Agpeya) — its prayers, psalms, and gospels for all seven canonical hours — is provided by the open coptic.io project and used with permission.',
      },
      {
        title: 'Typefaces',
        body: 'Cormorant Garamond and Spectral, under the SIL Open Font License.',
      },
    ],
    awaiting: 'Still to be supplied (from verified, official sources)',
    awaitingItems: [
      'Confirmation/clearance of the Synaxarium translation for release.',
      'The NKJV, if licensed (served online; KJV remains the offline default).',
    ],
  },

  hours: {
    head: 'The Hours',
    title: 'The Agpeya',
    subtitle: 'Seven times a day I praise You.',
    pray: 'Pray',
    kept: 'Kept',
    now: 'Now',
    saint: 'Commemoration of the day',
    noSaint: '⟨ commemoration to be supplied from a verified Synaxarium ⟩',
    ordo: 'Open the Ordo →',
    markKept: 'Mark this hour kept',
    lordHaveMercy: 'Lord, have mercy',
    draftNote: 'Prayer text to be supplied from a verified Agpeya.',
  },

  ordo: {
    head: 'The Ordo',
    title: 'Calendar of the Church',
    legend: { feast: 'Feast', fast: 'Fast', today: 'Today' },
  },

  word: {
    head: 'The Word',
    title: 'The Word',
    nowReading: 'Now reading',
    continue: 'Continue reading →',
    dayOf: (n: number, total: number) => `Day ${n} of ${total}`,
    markKept: 'Mark the day kept',
    tbd: '⟨ scripture text to be supplied from a verified, approved source ⟩',
    // Whole-Bible browse
    bible: 'The Holy Bible',
    browse: 'Browse the whole Bible →',
    oldTestament: 'The Old Testament',
    newTestament: 'The New Testament',
    // Reading plans (opt-in library + completions)
    plans: 'Reading plans',
    plansAvailable: 'Begin a plan',
    plansActive: 'Your plans',
    plansCompleted: 'Completed',
    start: 'Begin this plan →',
    completed: 'Completed',
    planDayProgress: (done: number, total: number) => `${done} of ${total} days kept`,
    noPlans: 'You are not following a plan yet.',
    // Commemoration of the day (the Synaxarium life), shown beneath the readings.
    commemoration: 'Commemoration of the day',
    noCommemoration: '⟨ commemoration to be supplied from a verified Synaxarium ⟩',
  },

  highlights: {
    head: 'What you have marked',
    title: 'Saved',
    searchPlaceholder: 'Search your marks…',
    empty: 'Nothing marked yet. Press and hold a passage to mark it.',
    noResults: 'No marks match that search.',
    save: 'Save',
    saveMark: 'Save the whole passage',
    saveSelection: 'Save selection',
    note: 'A note',
    notePlaceholder: 'A note on this passage…',
    colour: 'Colour',
    remove: 'Remove highlight',
    sources: { all: 'All', scripture: 'Scripture', synaxarium: 'Synaxarium' },
    count: (n: number) => `${n} ${n === 1 ? 'mark' : 'marks'}`,
  },

  learn: {
    head: 'Learn the Coptic tongue',
    title: 'The Coptic tongue',
    subtitle: 'Read, translate, and pronounce the language of the hymns.',
    level: 'level',
    xp: 'XP',
    milestonesLabel: 'milestones',
    path: 'Your path',
    begin: 'Begin →',
    review: 'Review →',
    locked: 'Locked',
    continueLesson: 'Continue',
    of: (a: number, b: number) => `${a} of ${b}`,
    daysProgress: (done: number, total: number) => `${done} / ${total} lessons`,
    // exercise prompts
    prompts: {
      'letter-name': 'Name this letter',
      'letter-sound': 'How is it sounded?',
      'name-letter': 'Which letter is this?',
      'word-meaning': 'What does it mean?',
      'word-read': 'How is it read?',
      'word-spell': 'Spell it in Coptic',
      'combo-sound': 'How do these letters sound?',
      'combo-read': 'How is this word read?',
      concept: '',
    } as Record<string, string>,
    gotIt: 'Got it →',
    correct: 'Correct',
    wrong: 'Not quite',
    listen: 'Tap to hear',
    audioSoon: 'Audio coming soon',
    check: 'Check',
    clear: 'Clear',
    // ranks
    rankLabel: 'Your rank',
    toNextRank: (n: number, rank: string) => `${n} more to ${rank}`,
    crownsLabel: 'crowns',
    // lesson states
    crownHint: 'Score 100% for the crown',
    needNinety: 'Score 90% to unlock the next level',
    // completion
    complete: 'Lesson complete',
    perfect: 'Perfect!',
    crownEarned: '☩ Crown earned',
    unlocked: 'Next level unlocked!',
    score: (correct: number, total: number) => `${correct} / ${total} correct`,
    earned: (n: number) => `+${n} XP`,
    milestoneEarned: 'Milestone earned',
    tryAgain: 'Try again',
    done: 'Done',
    // milestones timeline screen
    milestonesHead: 'Milestones on the way',
    milestonesTitle: 'Milestones',
    nextToUnlock: 'Next to unlock',
    earnedLabel: 'Earned',
    lockedLabel: 'Locked',
    milestonesProgress: (a: number, b: number) => `${a} of ${b} reached`,
  },

  reminders: {
    head: 'Reminders',
    title: 'A gentle word',
    subtitle: 'Choose what to be reminded of, and when. Never to shame — only to tend.',
    permission: 'Allow notifications in Settings to receive these.',
    at: 'at',
  },

  journal: {
    head: 'The commonplace book',
    title: 'The journal',
    prompt: 'Where did you sense God’s presence today?',
    take: 'Take up the pen →',
    save: 'Save',
    titlePlaceholder: 'A title',
    bodyPlaceholder: 'One ruled line is enough…',
    empty: 'No entries yet.',
    words: (n: number) => `${n} ${n === 1 ? 'word' : 'words'}`,
  },
} as const;
