/**
 * All user-facing strings — one place for voice consistency and future i18n
 * (CLAUDE.md "Voice": warm, literary, liturgical; never gamified or guilt-driven).
 */
export const copy = {
  tabs: { today: 'Today', hours: 'Hours', word: 'Word', coptic: 'Coptic', faith: 'Faith', rule: 'Rule', you: 'You', saved: 'Saved' },

  errorBoundary: {
    title: 'A moment of stillness',
    body: 'Something interrupted the page. Your saved rule and data are safe. Take a breath and try again.',
    retry: 'Try again',
  },

  today: {
    account: "The day's account",
    greeting: (name: string) => `Peace to you,\n${name}`,
    streak: 'day streak',
    kept: (n: number, m: number) => `Kept ${n} / ${m}`,
    ruleToday: 'Your rule today',
    commemoration: 'Commemoration of the day',
    journal: 'The journal',
    openJournal: 'Open the journal →',
    resting: 'Resting today',
    emptyTitle: 'Your rule is unwritten',
    emptyBody: 'Begin with a single practice. The lamp is tended, not stormed.',
    toRule: 'Open the Rule',
  },

  rule: {
    head: 'Your rule of life',
    title: 'A living rule',
    subtitle: 'Small and steady. Reorder, measure, or ease it whenever the season turns.',
    add: '＋ Add a practice',
    lighten: 'Lighten the rule for a season',
    groups: { prayer: 'Prayer', word: 'The Word', fast: 'The Fast', devotion: 'Devotion' },
  },

  checkin: {
    keep: 'Mark kept',
    part: 'Kept in part',
    cancel: 'Close',
  },

  lighten: {
    title: 'Tend, don’t storm',
    rest: 'Rest today — the flame stays lit',
    pause: 'Pause one practice',
    lighter: 'Keep a lighter rule',
    note: 'Rest days never break the streak.',
  },

  placeholder: {
    soon: 'Tended soon',
    body: 'This part of the book is still being illuminated.',
  },

  auth: {
    era: 'Anno Martyrum 1742',
    wordmark: 'Coptic Daily\nCompanion',
    promise:
      'A guiding light into the faith of the Copts — prayer, fasting, and the Word, one day at a time.',
    begin: 'Begin the journey',
    continueApple: 'Continue with Apple',
    signingIn: 'Signing in…',
    signInError: 'Sign-in did not complete. Please try again.',
    haveAccount: 'I already keep an account',
    guest: 'Continue without an account',
    or: 'or',
    withEmail: 'Continue with email',
    signUpTitle: 'Keep an account',
    signUpSub: 'Save your rule so it’s here whenever you return.',
    signInTitle: 'Welcome back',
    signInSub: 'Sign in to return to your rule.',
    email: 'Email',
    password: 'Password',
    createAccount: 'Create account',
    signIn: 'Sign in',
    toSignIn: 'Already have an account? Sign in',
    toSignUp: 'New here? Create an account',
    // Email confirmation — the 6-digit code step right after sign-up.
    confirmTitle: 'Check your email',
    confirmSub: (email: string) => `We sent a 6-digit code to ${email}. Enter it to confirm.`,
    code: 'Confirmation code',
    confirmCta: 'Confirm and continue',
    resend: 'Send a new code',
    resent: 'Sent. Check your inbox.',
    lockedFor: (seconds: number) => `Too many attempts. Try again in ${seconds}s.`,
    changeEmail: 'Use a different email',
    errors: {
      'invalid-email': 'That email does not look right.',
      'weak-password': 'Use at least eight characters.',
      'email-taken': 'An account already keeps that email.',
      'invalid-credentials': 'Those credentials do not match.',
      'invalid-code': 'That code is not right. Check it and try again.',
      'too-many-attempts': 'Too many attempts. Wait a minute, then try again.',
      'confirm-email': 'Check your inbox to confirm your email, then sign in.',
    } as Record<string, string>,
  },

  onboarding: {
    journeyKicker: 'The first question',
    journeyTitle: 'Where are you\non the journey?',
    journeySub: 'We shape your rule around your answer. Change it anytime.',
    nameLabel: 'Your first name',
    namePlaceholder: 'What shall we call you?',
    journey: {
      'grew-up': { title: 'I grew up in the Church', sub: 'Deepen a faith I know' },
      returning: { title: 'I am returning', sub: 'Finding my way back' },
      exploring: { title: 'I am exploring', sub: 'Curious about Coptic Orthodoxy' },
    },
    rhythmKicker: 'Your rule of life',
    rhythmTitle: 'Set the daily\nhours you will keep',
    rhythmSub: 'Small and steady. The lamp is tended, not stormed.',
    lightLamp: 'Light the lamp →',
    continue: 'Continue →',
    notifKicker: 'One last thing',
    notifTitle: 'A gentle word\nat the hour',
    notifSub:
      'Only when a practice is due, in a quiet voice. Never to shame, only to tend.',
    notifAllow: 'Allow reminders',
    notifSkip: 'Not now',

    // What brings you here (goals) — each maps to a part of the app.
    goalsKicker: 'What brings you here',
    goalsTitle: 'What brought you\nhere today?',
    goalsSub: 'Choose all that speak to you. We build around them.',
    goals: {
      fasts: { title: 'Keep the fasts & feasts', sub: 'Never miss a holy day' },
      prayer: { title: 'Pray the hours', sub: 'The Agpeya, morning to night' },
      word: { title: 'Read the Word daily', sub: 'The Gospels, a little each day' },
      coptic: { title: 'Learn the Coptic tongue', sub: 'Read and chant the hymns' },
      saints: { title: 'Walk with the saints', sub: 'A life from the Synaxarium' },
      journal: { title: 'Examine my days', sub: 'A line of reflection, kept' },
    } as Record<string, { title: string; sub: string }>,

    // Experience level.
    experienceKicker: 'Where you stand',
    experienceTitle: 'How settled is\nthe rhythm?',
    experienceSub: 'We begin where you are. There is no wrong answer.',
    experience: {
      new: { title: 'New to it', sub: 'Just beginning' },
      some: { title: 'Some experience', sub: 'I keep a little, here and there' },
      rooted: { title: 'It is part of my life', sub: 'A rhythm I already hold' },
    } as Record<string, { title: string; sub: string }>,

    // Goal previews — the "yep, we support that" reveals, keyed by goal.
    previewKicker: 'Here for you',
    previews: {
      fasts: { title: 'The fasts & feasts, kept', lines: ['The day’s fast or feast, always on Today.', 'Gentle notes so a fast never slips by.'] },
      prayer: { title: 'Pray the hours', lines: ['The Agpeya hours, ready when you are.', 'Keep each office with a quiet mark.'] },
      word: { title: 'Read the Word', lines: ['A reading plan and the day’s lectionary.', 'Highlight and keep what speaks to you.'] },
      coptic: { title: 'Learn the Coptic tongue', lines: ['A leveled path: letters, sounds, holy words.', 'Learn by playing, with milestones along the way.'] },
      saints: { title: 'Walk with the saints', lines: ['The saint commemorated each day.', 'A cloud of witnesses to keep you company.'] },
      journal: { title: 'Examine your days', lines: ['A simple journal. One ruled line is enough.', 'Tie a reflection to the day’s reading.'] },
    } as Record<string, { title: string; lines: string[] }>,

    // Reminder time.
    reminderKicker: 'A gentle word',
    reminderTitle: 'When shall we\ncall you to prayer?',
    reminderSub: 'One quiet cue a day, at a time that fits.',
    reminderParts: { morning: 'Morning', noon: 'Noon', evening: 'Evening' } as Record<string, string>,

    // Finish — the lamp-lit moment.
    finishTitle: 'The lamp is lit',
    finishSub: 'Your rule is set. Begin in peace.',
    finishCta: 'Enter →',
    back: 'Back',
  },

  you: {
    head: 'You',
    guestLabel: 'Guest',
    guestHint: 'Your rule, journal, and progress stay on this device only. An account begins its own rule, kept in sync across devices; what you tend as a guest remains here.',
    guestCta: 'Create an account',
    signOut: 'Sign out',
    switch: 'Switch account',
    addAccount: 'Create another account',
    reminders: 'Reminders',
    theme: 'Appearance',
    themeModes: [
      { key: 'light', label: 'Light' },
      { key: 'dark', label: 'Dark' },
      { key: 'system', label: 'System' },
    ] as const,
    marks: 'The marks',
    invite: 'Invite a friend',
    /** Mail/subject line when the share target has one (iOS Mail, Gmail). */
    inviteSubject: 'Coptic Daily Companion',
    /** The body of the invite; the App Store link is attached beside it. */
    inviteMessage:
      'I keep my rule of life with Coptic Daily Companion — prayer, the fast, and the Word, one day at a time. Come and see.',
    about: 'About & attributions',
    contact: 'Help & contact',
    privacy: 'Privacy policy',
    terms: 'Terms of service',
    support: 'Support the app',
    supportScreen: {
      title: 'Support the app',
      heading: 'Tend the lamp',
      body: 'This app is kept by one pair of hands and offered freely. If it has served your prayer, a gift helps keep the lamp lit — entirely as you wish, never required.',
      tipsTitle: 'A one-time gift',
      tipsHint: 'Whatever is on your heart.',
      subTitle: 'Become a supporter',
      subHint: 'A small gift each month or year.',
      restore: 'Restore purchases',
      thanks: 'Thank you. The lamp burns a little brighter.',
      supporterActive: 'You are a supporter of this app. Thank you for keeping the lamp lit.',
      unavailable: 'Support is unavailable right now. Please try again later.',
      // Required auto-renew disclosure for the subscription (App Review 3.1.2).
      legal:
        'Payment is charged to your Apple ID at confirmation. A subscription renews automatically unless cancelled at least 24 hours before the period ends. Manage or cancel anytime in your App Store account settings.',
    },
    exportData: 'Export my data',
    exportWorking: 'Preparing your data…',
    exportError: 'Could not prepare the export. Please try again.',
    deleteAccount: 'Delete account',
    deleteScreen: {
      title: 'Delete account',
      heading: 'Delete your account?',
      body: 'This permanently removes your account and all of its data — your rule, prayer logs, journal, highlights, reading progress, and both Coptic and Faith course progress. This cannot be undone.',
      hint: 'Consider exporting your data first.',
      confirmLabel: 'Type DELETE to confirm',
      confirmWord: 'DELETE',
      confirmCta: 'Delete my account',
      cancel: 'Keep my account',
      working: 'Deleting…',
      error: 'Could not delete the account. Please try again.',
    },
    journeyLabel: 'On the journey',
    stats: { streak: 'streak', prayers: 'prayers', wedfri: '% wed/fri' },
    streakTitle: 'The lamp, tended',
    streakBody: 'Keep one practice each day to tend the flame.',
    streakUnit: 'days kept in a row',
    settings: 'Settings',
    textSize: 'Reading text size',
    textSizes: [
      { key: 'sm', label: 'S' },
      { key: 'md', label: 'M' },
      { key: 'lg', label: 'L' },
      { key: 'xl', label: 'XL' },
    ] as const,
    fastingNuance: 'Show fish-allowed nuance',
    aboutBody:
      'Coptic Daily Companion keeps your rule on this device alone. Liturgical and scriptural texts are drawn from the verified sources credited below; anything not yet supplied is clearly marked as a placeholder.',
    attributionsTitle: 'Attributions & sources',
    attributions: [
      {
        title: 'Holy Scripture',
        body: 'The Holy Bible, King James Version (KJV) — public domain. The KJV is the historically approved English translation for Coptic Orthodox use.',
      },
      {
        title: 'The Synaxarium',
        body: 'Daily commemorations from the open “coptic-synaxarium” dataset (randogoth, Codeberg). English text by St. George Coptic Orthodox Church, Chicago. Used in draft pending written permission.',
      },
      {
        title: 'Daily readings · the Katameros',
        body: 'Lectionary references (which passages are read each day) from the Katameros API at katameros.app, an open-source project. The verse text shown is the King James Version.',
      },
      {
        title: 'The liturgical calendar',
        body: 'The Coptic calendar, fasts, and feasts are computed within the app (Anno Martyrum dating and the Julian Paschal computus) and cross-checked against published Coptic sources.',
      },
      {
        title: 'The Agpeya',
        body: 'The Coptic Book of Hours (the Agpeya) — its prayers, psalms, and gospels for all seven canonical hours — is provided by the open coptic.io project and used with permission.',
      },
      {
        title: 'Typefaces',
        body: 'Cormorant Garamond and Spectral, under the SIL Open Font License.',
      },
    ],
    awaiting: 'Still to be supplied (from verified, official sources)',
    awaitingItems: [
      'Confirmation/clearance of the Synaxarium translation for release.',
      'The NKJV, if licensed (served online; KJV remains the offline default).',
    ],
  },

  hours: {
    head: 'The Hours',
    title: 'The Agpeya',
    subtitle: 'Seven times a day I praise You.',
    pray: 'Pray',
    kept: 'Kept',
    now: 'Now',
    saint: 'Commemoration of the day',
    noSaint: '⟨ commemoration to be supplied from a verified Synaxarium ⟩',
    ordo: 'Open the Ordo →',
    markKept: 'Mark this hour kept',
    lordHaveMercy: 'Lord, have mercy',
    draftNote: 'Prayer text to be supplied from a verified Agpeya.',
  },

  ordo: {
    head: 'The Ordo',
    title: 'Calendar of the Church',
    legend: { feast: 'Feast', fast: 'Fast', today: 'Today' },
  },

  word: {
    head: 'The Word',
    title: 'The Word',
    nowReading: 'Now reading',
    continue: 'Continue reading →',
    dayOf: (n: number, total: number) => `Day ${n} of ${total}`,
    markKept: 'Mark the day kept',
    tbd: '⟨ scripture text to be supplied from a verified, approved source ⟩',
    // Whole-Bible browse
    bible: 'The Holy Bible',
    browse: 'Browse the whole Bible →',
    oldTestament: 'The Old Testament',
    newTestament: 'The New Testament',
    // Reading plans (opt-in library + completions)
    plans: 'Reading plans',
    plansAvailable: 'Begin a plan',
    plansActive: 'Your plans',
    plansCompleted: 'Completed',
    start: 'Begin this plan →',
    completed: 'Completed',
    planDayProgress: (done: number, total: number) => `${done} of ${total} days kept`,
    noPlans: 'You are not following a plan yet.',
    // Commemoration of the day (the Synaxarium life), shown beneath the readings.
    commemoration: 'Commemoration of the day',
    noCommemoration: '⟨ commemoration to be supplied from a verified Synaxarium ⟩',
  },

  highlights: {
    head: 'What you have marked',
    title: 'Saved',
    searchPlaceholder: 'Search your marks…',
    empty: 'Nothing marked yet. Press and hold a passage to mark it.',
    noResults: 'No marks match that search.',
    save: 'Save',
    saveMark: 'Save the whole passage',
    saveSelection: 'Save selection',
    note: 'A note',
    notePlaceholder: 'A note on this passage…',
    colour: 'Colour',
    remove: 'Remove highlight',
    sources: { all: 'All', scripture: 'Scripture', synaxarium: 'Synaxarium' },
    count: (n: number) => `${n} ${n === 1 ? 'mark' : 'marks'}`,
  },

  learn: {
    head: 'Learn the Coptic tongue',
    title: 'The Coptic tongue',
    subtitle: 'Read, translate, and pronounce the language of the hymns.',
    level: 'level',
    xp: 'XP',
    milestonesLabel: 'milestones',
    path: 'Your path',
    begin: 'Begin →',
    review: 'Review →',
    locked: 'Locked',
    continueLesson: 'Continue',
    of: (a: number, b: number) => `${a} of ${b}`,
    daysProgress: (done: number, total: number) => `${done} / ${total} lessons`,
    // exercise prompts
    prompts: {
      'letter-name': 'Name this letter',
      'letter-sound': 'How is it sounded?',
      'name-letter': 'Which letter is this?',
      'word-meaning': 'What does it mean?',
      'word-read': 'How is it read?',
      'word-spell': 'Spell it in Coptic',
      'combo-sound': 'How do these letters sound?',
      'combo-read': 'How is this word read?',
      concept: '',
    } as Record<string, string>,
    gotIt: 'Got it →',
    correct: 'Correct',
    wrong: 'Not quite',
    listen: 'Tap to hear',
    audioSoon: 'Audio coming soon',
    check: 'Check',
    clear: 'Clear',
    // ranks
    rankLabel: 'Your rank',
    toNextRank: (n: number, rank: string) => `${n} more to ${rank}`,
    crownsLabel: 'crowns',
    // lesson states
    crownHint: 'Score 100% for the crown',
    needNinety: 'Score 90% to unlock the next level',
    // completion
    complete: 'Lesson complete',
    perfect: 'Perfect!',
    crownEarned: '☩ Crown earned',
    unlocked: 'Next level unlocked!',
    score: (correct: number, total: number) => `${correct} / ${total} correct`,
    earned: (n: number) => `+${n} XP`,
    milestoneEarned: 'Milestone earned',
    tryAgain: 'Try again',
    done: 'Done',
    // milestones timeline screen
    milestonesHead: 'Milestones on the way',
    milestonesTitle: 'Milestones',
    nextToUnlock: 'Next to unlock',
    earnedLabel: 'Earned',
    lockedLabel: 'Locked',
    milestonesProgress: (a: number, b: number) => `${a} of ${b} reached`,
  },

  faith: {
    head: 'Know the faith',
    title: 'The Coptic faith',
    subtitle: 'Where the Church began, what it confesses, and what it leaves unsaid.',
    level: 'level',
    xp: 'XP',
    lampsLabel: 'lamps',
    creedLabel: 'creed',
    milestonesLabel: 'milestones',
    locked: 'Locked',
    begin: 'Begin',
    continueLesson: 'Continue',
    of: (a: number, b: number) => `${a} of ${b}`,
    // step prompts
    prompts: {
      teach: '',
      choice: 'Choose one',
      truefalse: 'True, or not?',
      order: 'Tap them in order',
      standing: 'Where does this stand?',
    } as Record<string, string>,
    gotIt: 'Go on \u2192',
    correct: 'Correct',
    wrong: 'Not quite',
    why: 'Why',
    sourceLabel: 'Source',
    sourcesLabel: 'Sources',
    unreviewed: 'Awaiting review',
    unreviewedNote: 'This card has not yet been reviewed by the project owner. It is visible in development builds only.',
    check: 'Check',
    clear: 'Clear',
    // ranks
    rankLabel: 'Your standing',
    toNextRank: (n: number, rank: string) => `${n} more to ${rank}`,
    // lesson states
    lampHint: 'Score 100% for the lamp',
    needNinety: 'Score 90% to unlock the next lesson',
    // completion
    complete: 'Lesson complete',
    perfect: 'Perfect!',
    lampEarned: '\u2739 Lamp earned',
    unlocked: 'Next lesson unlocked!',
    score: (correct: number, total: number) => `${correct} / ${total} correct`,
    earned: (n: number) => `+${n} XP`,
    milestoneEarned: 'Milestone earned',
    clauseUnsealed: 'Clause of the Creed unsealed',
    tryAgain: 'Try again',
    done: 'Done',
    // teaching design
    essentialsLabel: 'By the end of this unit you can',
    reviewLabel: 'Recollection',
    reviewIntro:
      'No new material. These are the things worth keeping, asked again now that time has passed \u2014 recalling them is what makes them stay.',
    // the creed seal
    creedHead: 'The Creed, clause by clause',
    creedTitle: 'The Creed',
    creedIntro:
      'Each unit you finish unseals one clause of the Creed \u2014 earned by learning what stands behind it.',
    creedProgress: (a: number, b: number) => `${a} of ${b} unsealed`,
    creedSealed: 'Sealed',
    creedUnsealBy: (unit: string) => `Unsealed by ${unit}`,
    creedNote:
      'The wording here is a plain description written for this app, not a liturgical translation. Pray the Creed from your own church\u2019s book.',
    // milestones
    milestonesHead: 'Milestones on the way',
    milestonesTitle: 'Milestones',
    nextToUnlock: 'Next to unlock',
    earnedLabel: 'Earned',
    lockedLabel: 'Locked',
    milestonesProgress: (a: number, b: number) => `${a} of ${b} reached`,
  },

  reminders: {
    head: 'Reminders',
    title: 'A gentle word',
    subtitle: 'Choose what to be reminded of, and when. Never to shame — only to tend.',
    permission: 'Allow notifications in Settings to receive these.',
    at: 'at',
  },

  journal: {
    head: 'The commonplace book',
    title: 'The journal',
    prompt: 'Where did you sense God’s presence today?',
    take: 'Take up the pen →',
    save: 'Save',
    titlePlaceholder: 'A title',
    bodyPlaceholder: 'One ruled line is enough…',
    empty: 'No entries yet.',
    words: (n: number) => `${n} ${n === 1 ? 'word' : 'words'}`,
  },
} as const;
