/**
 * GENERATED by scripts/gen-bible.mjs from content/bible/kjv/index.json — do not
 * edit by hand. The full 66-book canon (structural metadata only: names, chapter
 * counts, testament, canonical order). Book names + chapter counts are universal
 * structural facts, not scripture content.
 */

export const BOOK_IDS = ['genesis', 'exodus', 'leviticus', 'numbers', 'deuteronomy', 'joshua', 'judges', 'ruth', '1samuel', '2samuel', '1kings', '2kings', '1chronicles', '2chronicles', 'ezra', 'nehemiah', 'esther', 'job', 'psalms', 'proverbs', 'ecclesiastes', 'songofsolomon', 'isaiah', 'jeremiah', 'lamentations', 'ezekiel', 'daniel', 'hosea', 'joel', 'amos', 'obadiah', 'jonah', 'micah', 'nahum', 'habakkuk', 'zephaniah', 'haggai', 'zechariah', 'malachi', 'matthew', 'mark', 'luke', 'john', 'acts', 'romans', '1corinthians', '2corinthians', 'galatians', 'ephesians', 'philippians', 'colossians', '1thessalonians', '2thessalonians', '1timothy', '2timothy', 'titus', 'philemon', 'hebrews', 'james', '1peter', '2peter', '1john', '2john', '3john', 'jude', 'revelation'] as const;

export type BookId = (typeof BOOK_IDS)[number];

export type Testament = 'ot' | 'nt';

export interface BookMeta {
  readonly id: BookId;
  readonly name: string;
  /** Coptic-script heading (ornament), where one is used. */
  readonly coptic?: string;
  readonly chapters: number;
  readonly testament: Testament;
  /** 1-based canonical position (1–66). */
  readonly order: number;
}

export const BOOK_DATA: readonly BookMeta[] = [
  { id: 'genesis', name: "Genesis", chapters: 50, testament: 'ot', order: 1 },
  { id: 'exodus', name: "Exodus", chapters: 40, testament: 'ot', order: 2 },
  { id: 'leviticus', name: "Leviticus", chapters: 27, testament: 'ot', order: 3 },
  { id: 'numbers', name: "Numbers", chapters: 36, testament: 'ot', order: 4 },
  { id: 'deuteronomy', name: "Deuteronomy", chapters: 34, testament: 'ot', order: 5 },
  { id: 'joshua', name: "Joshua", chapters: 24, testament: 'ot', order: 6 },
  { id: 'judges', name: "Judges", chapters: 21, testament: 'ot', order: 7 },
  { id: 'ruth', name: "Ruth", chapters: 4, testament: 'ot', order: 8 },
  { id: '1samuel', name: "1 Samuel", chapters: 31, testament: 'ot', order: 9 },
  { id: '2samuel', name: "2 Samuel", chapters: 24, testament: 'ot', order: 10 },
  { id: '1kings', name: "1 Kings", chapters: 22, testament: 'ot', order: 11 },
  { id: '2kings', name: "2 Kings", chapters: 25, testament: 'ot', order: 12 },
  { id: '1chronicles', name: "1 Chronicles", chapters: 29, testament: 'ot', order: 13 },
  { id: '2chronicles', name: "2 Chronicles", chapters: 36, testament: 'ot', order: 14 },
  { id: 'ezra', name: "Ezra", chapters: 10, testament: 'ot', order: 15 },
  { id: 'nehemiah', name: "Nehemiah", chapters: 13, testament: 'ot', order: 16 },
  { id: 'esther', name: "Esther", chapters: 10, testament: 'ot', order: 17 },
  { id: 'job', name: "Job", chapters: 42, testament: 'ot', order: 18 },
  { id: 'psalms', name: "Psalms", chapters: 150, testament: 'ot', order: 19 },
  { id: 'proverbs', name: "Proverbs", chapters: 31, testament: 'ot', order: 20 },
  { id: 'ecclesiastes', name: "Ecclesiastes", chapters: 12, testament: 'ot', order: 21 },
  { id: 'songofsolomon', name: "Song of Solomon", chapters: 8, testament: 'ot', order: 22 },
  { id: 'isaiah', name: "Isaiah", chapters: 66, testament: 'ot', order: 23 },
  { id: 'jeremiah', name: "Jeremiah", chapters: 52, testament: 'ot', order: 24 },
  { id: 'lamentations', name: "Lamentations", chapters: 5, testament: 'ot', order: 25 },
  { id: 'ezekiel', name: "Ezekiel", chapters: 48, testament: 'ot', order: 26 },
  { id: 'daniel', name: "Daniel", chapters: 12, testament: 'ot', order: 27 },
  { id: 'hosea', name: "Hosea", chapters: 14, testament: 'ot', order: 28 },
  { id: 'joel', name: "Joel", chapters: 3, testament: 'ot', order: 29 },
  { id: 'amos', name: "Amos", chapters: 9, testament: 'ot', order: 30 },
  { id: 'obadiah', name: "Obadiah", chapters: 1, testament: 'ot', order: 31 },
  { id: 'jonah', name: "Jonah", chapters: 4, testament: 'ot', order: 32 },
  { id: 'micah', name: "Micah", chapters: 7, testament: 'ot', order: 33 },
  { id: 'nahum', name: "Nahum", chapters: 3, testament: 'ot', order: 34 },
  { id: 'habakkuk', name: "Habakkuk", chapters: 3, testament: 'ot', order: 35 },
  { id: 'zephaniah', name: "Zephaniah", chapters: 3, testament: 'ot', order: 36 },
  { id: 'haggai', name: "Haggai", chapters: 2, testament: 'ot', order: 37 },
  { id: 'zechariah', name: "Zechariah", chapters: 14, testament: 'ot', order: 38 },
  { id: 'malachi', name: "Malachi", chapters: 4, testament: 'ot', order: 39 },
  { id: 'matthew', name: "Matthew", coptic: 'Ⲕⲁⲧⲁ Ⲙⲁⲑⲑⲉⲟⲛ', chapters: 28, testament: 'nt', order: 40 },
  { id: 'mark', name: "Mark", coptic: 'Ⲕⲁⲧⲁ Ⲙⲁⲣⲕⲟⲛ', chapters: 16, testament: 'nt', order: 41 },
  { id: 'luke', name: "Luke", coptic: 'Ⲕⲁⲧⲁ Ⲗⲟⲩⲕⲁⲛ', chapters: 24, testament: 'nt', order: 42 },
  { id: 'john', name: "John", coptic: 'Ⲕⲁⲧⲁ Ⲓⲱⲁⲛⲛⲏⲛ', chapters: 21, testament: 'nt', order: 43 },
  { id: 'acts', name: "Acts", chapters: 28, testament: 'nt', order: 44 },
  { id: 'romans', name: "Romans", chapters: 16, testament: 'nt', order: 45 },
  { id: '1corinthians', name: "1 Corinthians", chapters: 16, testament: 'nt', order: 46 },
  { id: '2corinthians', name: "2 Corinthians", chapters: 13, testament: 'nt', order: 47 },
  { id: 'galatians', name: "Galatians", chapters: 6, testament: 'nt', order: 48 },
  { id: 'ephesians', name: "Ephesians", chapters: 6, testament: 'nt', order: 49 },
  { id: 'philippians', name: "Philippians", chapters: 4, testament: 'nt', order: 50 },
  { id: 'colossians', name: "Colossians", chapters: 4, testament: 'nt', order: 51 },
  { id: '1thessalonians', name: "1 Thessalonians", chapters: 5, testament: 'nt', order: 52 },
  { id: '2thessalonians', name: "2 Thessalonians", chapters: 3, testament: 'nt', order: 53 },
  { id: '1timothy', name: "1 Timothy", chapters: 6, testament: 'nt', order: 54 },
  { id: '2timothy', name: "2 Timothy", chapters: 4, testament: 'nt', order: 55 },
  { id: 'titus', name: "Titus", chapters: 3, testament: 'nt', order: 56 },
  { id: 'philemon', name: "Philemon", chapters: 1, testament: 'nt', order: 57 },
  { id: 'hebrews', name: "Hebrews", chapters: 13, testament: 'nt', order: 58 },
  { id: 'james', name: "James", chapters: 5, testament: 'nt', order: 59 },
  { id: '1peter', name: "1 Peter", chapters: 5, testament: 'nt', order: 60 },
  { id: '2peter', name: "2 Peter", chapters: 3, testament: 'nt', order: 61 },
  { id: '1john', name: "1 John", chapters: 5, testament: 'nt', order: 62 },
  { id: '2john', name: "2 John", chapters: 1, testament: 'nt', order: 63 },
  { id: '3john', name: "3 John", chapters: 1, testament: 'nt', order: 64 },
  { id: 'jude', name: "Jude", chapters: 1, testament: 'nt', order: 65 },
  { id: 'revelation', name: "Revelation", chapters: 22, testament: 'nt', order: 66 },
];
