/**
 * Generate the typed Bible canon + KJV loader map from the ingested manifest.
 *
 * Reads  content/bible/kjv/index.json  (the 66-book manifest produced by
 * ingest-kjv.mjs) and writes two GENERATED, do-not-edit-by-hand files:
 *   - src/domain/content/bible.gen.ts  (BOOK_IDS tuple + BOOK_DATA table)
 *   - src/content/kjv.gen.ts           (static per-book lazy require map)
 *
 * Keeping these generated from the manifest means the navigable canon can never
 * drift from the bundled JSON. The first 39 books are the Old Testament, the
 * last 27 the New (canonical order, as the manifest is ordered).
 *
 * Run:  node scripts/gen-bible.mjs
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const MANIFEST = join(ROOT, 'content', 'bible', 'kjv', 'index.json');

// Coptic-script ornaments for the books that carry one in the reader heading.
const COPTIC = {
  matthew: 'Ⲕⲁⲧⲁ Ⲙⲁⲑⲑⲉⲟⲛ',
  mark: 'Ⲕⲁⲧⲁ Ⲙⲁⲣⲕⲟⲛ',
  luke: 'Ⲕⲁⲧⲁ Ⲗⲟⲩⲕⲁⲛ',
  john: 'Ⲕⲁⲧⲁ Ⲓⲱⲁⲛⲛⲏⲛ',
};

const OT_COUNT = 39; // Genesis…Malachi; the remaining 27 are the New Testament.

const manifest = JSON.parse(await readFile(MANIFEST, 'utf8'));
const books = manifest.books;
if (!Array.isArray(books) || books.length !== 66) {
  throw new Error(`expected 66 books in manifest, found ${books?.length}`);
}

const rows = books.map((b, i) => ({
  id: b.id,
  name: b.book,
  coptic: COPTIC[b.id],
  chapters: b.chapters,
  testament: i < OT_COUNT ? 'ot' : 'nt',
  order: i + 1,
}));

const idsLiteral = rows.map((r) => `'${r.id}'`).join(', ');
const dataRows = rows
  .map((r) => {
    const coptic = r.coptic ? ` coptic: '${r.coptic}',` : '';
    return `  { id: '${r.id}', name: ${JSON.stringify(r.name)},${coptic} chapters: ${r.chapters}, testament: '${r.testament}', order: ${r.order} },`;
  })
  .join('\n');

const bibleGen = `/**
 * GENERATED by scripts/gen-bible.mjs from content/bible/kjv/index.json — do not
 * edit by hand. The full 66-book canon (structural metadata only: names, chapter
 * counts, testament, canonical order). Book names + chapter counts are universal
 * structural facts, not scripture content.
 */

export const BOOK_IDS = [${idsLiteral}] as const;

export type BookId = (typeof BOOK_IDS)[number];

export type Testament = 'ot' | 'nt';

export interface BookMeta {
  readonly id: BookId;
  readonly name: string;
  /** Coptic-script heading (ornament), where one is used. */
  readonly coptic?: string;
  readonly chapters: number;
  readonly testament: Testament;
  /** 1-based canonical position (1–66). */
  readonly order: number;
}

export const BOOK_DATA: readonly BookMeta[] = [
${dataRows}
];
`;

const loaderRows = rows
  .map((r) => `  ${/^[a-z]/.test(r.id) ? r.id : `'${r.id}'`}: () => require('../../content/bible/kjv/${r.id}.json'),`)
  .join('\n');

const kjvGen = `/**
 * GENERATED by scripts/gen-bible.mjs — do not edit by hand.
 *
 * Lazy loaders for every bundled public-domain KJV book. Each \`require\` is a
 * static string literal (Metro requires this) wrapped in a closure, so a book's
 * JSON is only parsed the first time that book is opened — the bundle stays lean.
 * Data: content/bible/kjv/ (see scripts/ingest-kjv.mjs).
 */
import type { BookId } from '../domain/content/bible';

type Loaded = { chapters: { chapter: number; verses: { n: number; text: string }[] }[] };

export const kjvLoaders: Record<BookId, () => Loaded> = {
${loaderRows}
};
`;

await writeFile(join(ROOT, 'src', 'domain', 'content', 'bible.gen.ts'), bibleGen);
await writeFile(join(ROOT, 'src', 'content', 'kjv.gen.ts'), kjvGen);
console.log(`Generated bible.gen.ts + kjv.gen.ts for ${rows.length} books.`);
